### ISSUE TITLE
Plain text component has "initialValue" warning message

### ISSUE THREAD

**Issue by yhrchan** [data-driven-forms/form-builder#48]
Checked out the code and run "yarn start". Dragged the "Plain text" component to the form builder and when something is typed into the "Initial value" text box, in the debugger there's a warning/error message. However, this is not happening in the Form Builder in the documentation site -> https://data-driven-forms.org/live-editor

Warning: React does not recognize the `initialValue` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `initialvalue` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Context.Consumer)
    in Typography (created by ResizeObserver)
    in ResizeObserver (created by LocaleReceiver)
    in LocaleReceiver (created by Base)
    in Base (created by Paragraph)
    in Paragraph (created by PlainText)
    in article (created by Context.Consumer)
    in Typography (created by PlainText)
    in PlainText (created by ComponentWrapper)
    in div (created by ComponentWrapper)
    in ComponentWrapper (created by Draggable)
    in div (created by FieldLayout)
    in div (created by FieldLayout)
    in FieldLayout (created by Draggable)
    in div (created by Draggable)
    in Draggable (created by ConnectFunction)
    in ConnectFunction (created by PrivateDraggable)
    in PrivateDraggable (created by PublicDraggable)
    in PublicDraggable
    in Unknown (created by MemoizedField)
    in MemoizedField (created by Droppable)
    in div (created by Droppable)
    in div (created by FormContainer)
    in FormContainer (created by Droppable)

**Comment by Hyperkid123** [comment]
@yhrchan 

Thea problem here is that the `plain-text` component type is not interactive and it should have the `initialValue` property, nor the `validation` tab. We will have to add some flags to identify (non)interactive fields to prevent the properties editor from showing the initial value and other interactive only attributes.

**Comment by rvsia** [comment]
Fixed in `@data-driven-forms/form-builder@0.0.11-rc4`
